version: "3"
services:
  postgresDB:
    image: jaroslawwitek89/car-service-db:latest
    network_mode: bridge
    container_name: postgres-db-instance
    volumes:
      - postgres-data:/var/lib/postgresql/data
    expose:
    - 5432
    ports:
      - 5432:5432
    environment:
         - POSTGRES_PASSWORD=admin
         - POSTGRES_USER=postgres
         - POSTGRES_DB=testdb
#         - POSTGRES_DB=postgres
#        - POSTGRES_DB=testdb
    restart: unless-stopped
# APP*****************************************
  car-service-app:
    image: jaroslawwitek89/car-service-app:latest
    network_mode: bridge
    container_name: car-service-app-instance
    expose:
      - 8090
    ports:
      - 8090:8090
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresDB/postgres
    restart: unless-stopped
    depends_on:
      - postgresDB
    links:
      - postgresDB
volumes:
  postgres-data: